services:
  baxus-monitor:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces/baxus-monitor:cached
    command: sleep infinity
    init: true
    security_opt:
      - no-new-privileges:true
    cap_add:
      - DAC_OVERRIDE