services:
  alert-sender:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces/alert-sender:cached
    command: sleep infinity
    init: true
    security_opt:
      - no-new-privileges:true
    cap_add:
      - DAC_OVERRIDE